### ISSUE TITLE
First Half of Page 1

### ISSUE THREAD

**Issue by rubuy-74** [rubuy-74/1984-git#1]
Write the following in the Page 1:

`Era um dia claro e frio de abril e os relógios mar-
cavam treze horas. Winston Smith, seu queixo
abaixado de encontro ao peito numa tentati-
va de escapar do vento infame, passou rápido
pelas portas de vidro das Mansões da Vitória, ain-
da que não rápido o suficiente para evitar que um
montinho de poeira fina entrasse junto com ele.`

**Comment by GuiCNunes** [comment]
I will work on this
