### ISSUE TITLE
Second Half of Page 1

### ISSUE THREAD

**Issue by rubuy-74** [rubuy-74/1984-git#2]
Write the following in Page 2:

`O hall de entrada tinha cheiro de repolho cozido e
tapetes velhos de retalhos. Um cartaz grande de-
mais para ser exposto internamente estava fixado
em uma das extremidades. Mostrava simplesmen-
te um rosto enorme, mais de um metro de largura:
o rosto de um homem de cerca de 45 anos, com um
bigode preto farto e traços acidentalmente boni-
tos. Winston alcançou as escadas. Não adiantava
chamar o elevador. Raramente estava funcionan-
do, mesmo em momentos melhores, e atualmen-
te a energia elétrica ficava desligada durante o dia.
Isso era parte de um esforço econômico em pre-
paração para a Semana do Ódio. O apartamento
ficava no sétimo andar e Winston, que tinha 39
anos de idade e uma úlcera varicosa logo acima`

**Comment by R0drig0-P** [comment]
i will work on this
